print ("    TUGAS PYTHON    ")
print ()
print ("Peogram Biodata")
print ()
nama = input("Masukkan Nama Anda : ")
panggilan = input("Masukkan Panggilan : ")
sekolah = input("Masukkan Nama Sekolah Anda : ")
nim = input("NIM Anda : ")
ttgl = input("Masukkan Tanggal Lahir : ")
tmplhr = input("masukkan Tempat Lahir : ")
tlpn = input("Masukkan Nomor HP : ")
alamat = input("Masukkan Alamat : ")
umur = input("Masukkan Umur Anda : ")
print()
print("Assalamualaikum")
print()
print("Nama saya {0} Umur saya {8} dan Saya biasa di panggil {1}"
      "Saya bersekolah di {2}, dengan NIM : {3}, Saya lahir tanggal {5} {4}"
      "Nomor telepon saya : {6}, dan saya tinggal di {7}".format(nama, umur, panggilan, sekolah, nim, ttgl, tmplhr, tlpn, alamat))
print()
print("Thank you")
